apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: ambassador
  spec:
    selector:
      app:  ambassador-svc
    type: NodePort
    ports:
    - name:  ambassador-port
      port:  80
      # targetPort:  8080
- apiVersion: v1
  kind: Pod
  metadata:
    name: ambassador-example
    labels:
      app: ambassador-svc
  spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports: 
      - containerPort: 80
      volumeMounts:
      - name: logging-vol
        mountPath: /var/log/nginx
    volumes:
      - name:  logging-vol
        persistentVolumeClaim: 
          claimName: logging-pvc
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: logging-pv
  spec:
    accessModes: 
    - ReadWriteOnce
    hostPath:
      path: /mnt/hgfs/K8s-Storage/ambassador/logging-pv
      type: DirectoryOrCreate
    capacity: 
      storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: logging-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    volumeName: logging-pv
    selector:
      matchLabels: 
        name: logging-pv
    resources:
      requests:
        storage: 200Mi
