apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: access-secrets
    labels:
      username: "fred"
  data:
    password: UGFzc3cwcmQ=

- apiVersion: v1
  kind: Pod
  metadata:
    name: secret-test
  spec:
    containers:
    - name: secret-test
      image: 10.10.0.100:6088/simplemicroservice:1.0
      env:
      - name: MY_PARM
        value: "-c /tmp/config.conf"
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: access-secrets
            key: password
      volumeMounts:
      - mountPath: "/tmp/secrets"
        name: secrets-vol
    volumes:
    - name: secrets-vol
      secret:
        secretName: access-secrets
