apiVersion: v1
kind: Pod
metadata:
  name: simple-secret-config
  labels:
    # key/value needs to match the selector in the Service.
    app: simpleservice
spec:
  containers:
  - name: simplemicroservice
    image: 10.10.0.100:6088/simplemicroservice:1.0
    ports:
    - containerPort: 10000
    env:
    - name: MICROSERVICE_VERSION
      valueFrom:
        secretKeyRef: 
          name: version-secret
          key: version