apiVersion: v1
kind: List
items:

# This PV is created on minikube
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: logging-pv
  spec:
    accessModes:
      - "ReadWriteOnce"
    persistentVolumeReclaimPolicy: Retain
    # The storage class is needed because it will impact when the volume gets mounted.
    storageClassName: local-storage
    hostPath:
      path: /mnt/hgfs/K8s-Storage/logs
    capacity:
      storage: 1Gi

# This PV is created on minikube
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local-pv
  spec:
    accessModes:
      - "ReadWriteMany"
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    capacity:
      storage: 1Gi
    hostPath:
      path: /mnt/hgfs/K8s-Storage/local