apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: simple-pv-service
  spec:
    containers:
    - name: simplemicroservice
      image: 10.10.0.100:6088/simplemicroservice:1.0
      ports:
      - containerPort: 10000
      # readinessProbe:
      #   httpGet:
      #     path: "/"
      #     port: 10001
      # livenessProbe:
      #   httpGet:
      #     path: "/liveness"
      #     port: 10001
      #   periodSeconds: 15
      resources:
        limits:
          cpu: 1
          memory: 1Gi
      volumeMounts:
        - name: logging-vol
          mountPath: /logs
        - name: local-storage-vol
          mountPath: /local-storage-vol
    volumes:
    - name: logging-vol
      persistentVolumeClaim:
        claimName: logging-pvc
    - name: local-storage-vol
      persistentVolumeClaim:
        claimName: local-storage-pvc

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: logging-pvc
  spec:
    accessModes:
    - ReadWriteMany
    # this may cause an issue when run with a different PV
    storageClassName: local-storage
    # selector: logging-pv
    volumeName: logging-pv
    resources:
      requests:
        storage: 200Mi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: local-storage-pvc
  spec:
    accessModes:
    - ReadWriteMany
    # this may cause an issue when run with a different PV
    storageClassName: local-storage
    resources:
      requests:
        storage: 200Mi
