apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: secret-access-sa

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: secret-access-cr
  rules:
  - apiGroups: [""] # "" indicates the core API Group
    resources: ["secrets"]
    verbs: ["get","list"]

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: secret-access-crb
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: secret-access-cr
  subjects:
  - kind: ServiceAccount
    name: secret-access-sa
    namespace: default

- apiVersion: v1
  kind: Pod
  metadata:
    name: serviceaccount
  spec:
    containers:
    - name: serviceaccount
      image: nginx:latest
    serviceAccountName: secret-access-sa
