apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: secret-access-sa
- apiVersion: v1
  kind: Pod
  metadata:
    name: service-account-service
  spec:
    serviceAccountName: secret-access-sa
    containers:
    - name: simplemicroservice
      image: 10.10.0.100:6088/simplemicroservice:1.0
      ports:
      - containerPort: 10000
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: secret-access-cr
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: secret-rb
  subjects:
  - kind: ServiceAccount
    name: secret-access-sa
    namespace: default
  roleRef:
    kind: ClusterRole
    name: secret-access-cr
    # This is not really required because it refaults to: rbac.authorization.k8s.io
    apiGroup: rbac.authorization.k8s.io