apiVersion: v1
kind: Pod
metadata:
  name: service-account-service
  labels:
    # key/value needs to match the selector in the Service.
    app: simpleservice
spec:
  serviceAccountName: secret-access-sa
  containers:
  - name: simplemicroservice
    image: 10.10.0.100:6088/simplemicroservice:1.0
    ports:
    - containerPort: 10000