apiVersion: v1
items:
# Define the deployment.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: simpledimple
  spec:
    replicas: 2
    selector:
      # Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment. It must match the pod template's labels.
      matchLabels:
        app: simpleservice
    template:
      metadata:
        labels:
          app: simpleservice
      spec:
        containers:
        - name: simpleservice    
          image: simplemicroservice:0.1
          ports:
          - containerPort: 10000
        volumes:
        - name: simpleservice-claim0
          persistentVolumeClaim:
            claimName: simpleservice-claim0
            readOnly: false
# Define the PVC for the pod.
- apiVersion: apps/v1
  kind: PersistentVolumeClaim
  metadata:
    name: simpleservice-claim0
  spec:
