apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleservice-deployment
  labels:
    # Label selector for pods. Existing ReplicaSets whose pods are selected by this
    # will be the ones affected by this deployment. It must match the pod template's labels.
    app: simpleservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleservice
  template:
    metadata:
      labels:
        app: simpleservice
    spec:
      containers:  
      - name: simplemicroservice
        image: 10.10.0.100:6088/microservice:0.2
        ports:
        - containerPort: 10000
        # Hard code the node port so it is easier for test cases.
        - nodePort: 32000