apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: simpleservice
  type: NodePort
  ports:
  - name: simple
    port: 10000
    nodePort: 32000