apiVersion: v1
kind: Pod
metadata:
  name: simplemicroservice
  labels:
    # key/value needs to match the selector in the Service.
    app: simpleservice
spec:
  containers:
  - name: simplemicroservice
    image: 10.10.0.100:6088/microservice:0.2
    ports:
    - containerPort: 10000
