apiVersion: v1
kind: Pod
metadata:
  name: security-context-test
  labels:
    # key/value needs to match the selector in the Service.
    app: simpleservice
spec:  
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true    # Restricts the container to not run as root. This will fail without runAsUser
  containers:
  - name: simplemicroservice
    image: 10.10.0.100:6088/simplemicroservice:1.0
    ports:
    - containerPort: 10000