apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: weblog-pv
    labels:
      type: local
  spec:
    storageClassName: manual
    accessModes: 
    - ReadWriteOnce
    hostPath:
      path: /tmp/weblog
      type: DirectoryOrCreate
    capacity: 
      storage: 500Mi
 
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: weblog-pvc
  spec:
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 200Mi
        
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: sidecar-example-logs-pv
  spec:
    accessModes: 
    - ReadWriteMany
    capacity: 
      storage: 10Gi
    nfs:
      path: /K8s-Training/logs/weblogs
      server: 10.10.0.100
    persistentVolumeReclaimPolicy: Retain

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sidecar-example-logs-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 2Gi
    volumeName: sidecar-example-logs-pv

- apiVersion: v1
  kind: Pod
  metadata:
    name: sidecar-example
    labels:
      app: webserver
  spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports: 
      - containerPort: 80
      volumeMounts:
      - name: logging-vol
        mountPath: /var/log/nginx
    - name: fdlogger
      image: fluent/fluentd
      volumeMounts:
      - name: logging-vol
        mountPath: /var/log
      - name: k8s-training-storage
        mountPath: /tmp/K8s-Training
    volumes:
      - name:  logging-vol
        persistentVolumeClaim: 
          claimName: weblog-pvc
      - name: k8s-training-storage
        persistentVolumeClaim:
          claimName: sidecar-example-logs-pvc

- apiVersion: v1
  kind: Service
  metadata:
    name: sidecar-svc
  spec:
    selector:
      app:  webserver
    type: NodePort
    ports:
    - name:  sidecar-port
      port:  80
      nodePort:  32000