apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: simpleservice
  spec:
    selector:
      # Loadbalance traffic across Pods matching
      # this label selector
      app: simpleservice
    type: NodePort
    ports:
    - name: simple
      port: 10000
      nodePort: 32000
- apiVersion: v1
  kind: Pod
  metadata:
    name: simplemicroservice
    labels:
      # key/value needs to match the selector in the Service.
      app: simpleservice
  spec:
    containers:
    - name: simplemicroservice
      image: 10.10.0.100:6088/simplemicroservice:1.0
      ports:
      - containerPort: 10000
    #   volumeMounts:
    #   - name: test-volume
    #     mountPath: /data
    # volumes:
    # - name: test-volume
    #   hostPath:
    #     path: /test-volume-mount
    #     type: DirectoryOrCreate